---

- name: Factory reset devices
  hosts: CLOUDVISION
  connection: local
  gather_facts: no
  vars:
    CVP_DEVICES:
      - fqdn: "dc1-leaf1a"
        parentContainerName: ""
      - fqdn: "dc1-leaf1b"
        parentContainerName: ""
      - fqdn: "dc1-leaf2a"
        parentContainerName: ""
      - fqdn: "dc1-leaf2b"
        parentContainerName: ""
      - fqdn: "dc1-spine1"
        parentContainerName: ""
      - fqdn: "dc1-spine2"
        parentContainerName: ""

  tasks:
  - name: remove device
    arista.cvp.cv_device_v3:
        devices: '{{CVP_DEVICES}}'
        state: factory_reset

#  - name: Pause to wait until devcies are rebooted/rediscovered
#    ansible.builtin.pause:
#      minutes: 8
#
#- name: remove container topology on CVP
#  hosts: CLOUDVISION
#  connection: local
#  gather_facts: no
#  vars:
#    verbose: False
#    CVP_CONTAINERS:
#        DC1_L3_LEAVES:
#            parentContainerName: DC1
#        DC1_SPINES:
#            parentContainerName: DC1
#        DC1:
#            parentContainerName: FABRIC
#        FABRIC:
#            parentContainerName: Tenant
#
#  tasks:
#    - name: 'running cv_container'
#      arista.cvp.cv_container_v3:
#        topology: "{{CVP_CONTAINERS}}"
#        state: absent
#
#
#  name: Delete configlets
#  hosts: CLOUDVISION
#  connection: local
#  gather_facts: no
#  vars:
#    configlet_list:
#      AVD-FABRIC-*
# 
#  tasks:
#    - name: "delete config"
#      arista.cvp.cv_configlet_v3:
#        configlets: "{{configlet_list}}"
#        state: absent
#      register: cvp_configlet