---
- name: Clenup CVP in default configuration
  hosts: cvp
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: run CVP provisioning
      import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
#        container_root: 'DC1'
#        configlets_prefix: 'AVD'
#        device_filter: 'dc1-'
#        state: absent
        cv_collection: v3 # (3)!
        fabric_name: FABRIC # (4)!

